partial namespace console {
  // https://github.com/whatwg/console/issues/27
  undefined exception(any msg);

  // https://github.com/whatwg/console/issues/144
  undefined profile(optional DOMString profileName);
  undefined profileEnd(optional DOMString profileName);

  // https://github.com/whatwg/console/issues/140
  undefined timeStamp(DOMString label);
};
