[Exposed=(Window,Worker)]
interface Directory {
  [Throws]
  readonly attribute DOMString name;
};

[Exposed=(Window,Worker)]
partial interface Directory {
  [Throws]
  readonly attribute DOMString path;

  [NewObject]
  Promise<sequence<(File or Directory)>> getFilesAndDirectories();

  [NewObject]
  Promise<sequence<File>> getFiles(optional boolean recursiveFlag = false);
};
