partial interface Document {
  attribute EventHandler onscrollsnapchange;
  attribute EventHandler onscrollsnapchanging;
};

partial interface HTMLElement {
  attribute EventHandler onafterscriptexecute;
  attribute EventHandler onbeforescriptexecute;
  attribute EventHandler oncompositionend;
  attribute EventHandler oncompositionstart;
  attribute EventHandler oncompositionupdate;
  attribute EventHandler oncontentvisibilityautostatechange;
  attribute EventHandler onscrollsnapchange;
  attribute EventHandler onscrollsnapchanging;
  attribute EventHandler onwebkitmouseforcechanged;
  attribute EventHandler onwebkitmouseforcedown;
  attribute EventHandler onwebkitmouseforceup;
  attribute EventHandler onwebkitmouseforcewillbegin;
};

partial interface Window {
  attribute EventHandler onscrollsnapchange;
  attribute EventHandler onscrollsnapchanging;
};

partial interface HTMLCanvasElement {
  attribute EventHandler oncontextlost;
  attribute EventHandler oncontextrestored;
  attribute EventHandler onwebglcontextcreationerror;
  attribute EventHandler onwebglcontextlost;
  attribute EventHandler onwebglcontextrestored;
};

partial interface HTMLDialogElement {
  attribute EventHandler oncancel;
  attribute EventHandler onclose;
};

partial interface HTMLFormElement {
  attribute EventHandler onformdata;
  attribute EventHandler onreset;
  attribute EventHandler onsubmit;
};

partial interface HTMLInputElement {
  attribute EventHandler oncancel;
  attribute EventHandler oninvalid;
  attribute EventHandler onselect;
  attribute EventHandler onselectionchange;
};

partial interface HTMLMediaElement {
  attribute EventHandler onabort;
  attribute EventHandler oncanplay;
  attribute EventHandler oncanplaythrough;
  attribute EventHandler ondurationchange;
  attribute EventHandler onemptied;
  attribute EventHandler onended;
  attribute EventHandler onloadeddata;
  attribute EventHandler onloadedmetadata;
  attribute EventHandler onloadstart;
  attribute EventHandler onpause;
  attribute EventHandler onplay;
  attribute EventHandler onplaying;
  attribute EventHandler onprogress;
  attribute EventHandler onratechange;
  attribute EventHandler onseeked;
  attribute EventHandler onseeking;
  attribute EventHandler onstalled;
  attribute EventHandler onsuspend;
  attribute EventHandler ontimeupdate;
  attribute EventHandler onvolumechange;
  attribute EventHandler onwaiting;
};

partial interface HTMLSlotElement {
  attribute EventHandler onslotchange;
};

partial interface HTMLTextAreaElement {
  attribute EventHandler onselect;
  attribute EventHandler onselectionchange;
};

partial interface HTMLTrackElement {
  attribute EventHandler oncuechange;
};

partial interface HTMLVideoElement {
  attribute EventHandler onresize;
};

partial interface Node {
  attribute EventHandler onselectstart;
};

partial interface SVGAnimationElement {
  attribute EventHandler onbeginEvent;
  attribute EventHandler onendEvent;
  attribute EventHandler onrepeatEvent;
};

partial interface WorkerGlobalScope {
  attribute EventHandler onsecuritypolicyviolation;
};

partial interface XMLHttpRequest {
  attribute EventHandler onabort;
  attribute EventHandler onerror;
  attribute EventHandler onload;
  attribute EventHandler onloadend;
  attribute EventHandler onloadstart;
  attribute EventHandler onprogress;
  attribute EventHandler ontimeout;
};

partial interface XMLHttpRequestUpload {
  attribute EventHandler onabort;
  attribute EventHandler onerror;
  attribute EventHandler onload;
  attribute EventHandler onloadend;
  attribute EventHandler onloadstart;
  attribute EventHandler onprogress;
  attribute EventHandler ontimeout;
};
