partial interface MediaStream {
  attribute EventHandler onactive;
  attribute EventHandler oninactive;
};

[Exposed=Window]
interface MediaStreamEvent : Event {
  constructor();
  readonly attribute MediaStream stream;
};
