[Exposed=*, LegacyNamespace=WebAssembly]
interface Exception {
  constructor();

  undefined getArg();
  boolean is();

  readonly attribute DOMString stack;
};

[Exposed=*, LegacyNamespace=WebAssembly] interface CompileError : Exception {
  constructor();
};
[Exposed=*, LegacyNamespace=WebAssembly] interface LinkError : Exception {
  constructor();
};
[Exposed=*, LegacyNamespace=WebAssembly] interface RuntimeError : Exception {
  constructor();
};

[Exposed=*, LegacyNamespace=WebAssembly]
interface Tag {
  constructor();

  readonly attribute DOMString type;
};
