// https://github.com/gpuweb/gpuweb/pull/4370
partial interface GPUCommandEncoder {
  undefined writeTimestamp();
};

partial interface GPUComputePassEncoder {
  undefined writeTimestamp();
};

partial interface GPURenderPassEncoder {
  undefined writeTimestamp();
};

// Removed from the spec

partial interface GPUAdapter {
  undefined requestAdapterInfo();
  readonly attribute boolean isFallbackAdapter;
};

partial interface GPUSupportedLimits {
  attribute long maxInterStageShaderComponents;
};
