name: Test

on:
  push:
  pull_request:

permissions:
  contents: read
  pull-requests: read # Required to read pull request metadata for the diff workflow.

env:
  FORCE_COLOR: 3

concurrency:
  group: test-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest
    name: Test
    env:
      BCD_DIR: ./browser-compat-data
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
      - name: Checkout browser-compat-data
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          repository: mdn/browser-compat-data
          path: browser-compat-data
          persist-credentials: false
      - name: Setup NodeJS
        uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          node-version-file: ".nvmrc"
      - name: Prepare browser-compat-data
        run: npm ci
        working-directory: browser-compat-data
      - run: npm ci
      - run: npm run format
      - run: npm run build
      - run: npm run unittest
      # ensure we can start the server without dev dependencies
      - name: Production smoke test
        run: |
          npm ci --production
          npm start &
          npx wait-on -t 10000 -v http://localhost:8080
        env:
          NODE_ENV: production

  diff-features:
    if: github.event_name == 'pull_request'
    name: Diff features
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-${{ github.event.pull_request.number }}-diff-features
      cancel-in-progress: true
    env:
      PUPPETEER_SKIP_DOWNLOAD: 1
    steps:
      - name: Checkout collector (base)
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          ref: ${{ github.base_ref }}
          path: base
          persist-credentials: false
          submodules: true
      - name: Checkout collector (PR)
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          path: pr
          persist-credentials: false
          submodules: true
      - name: Checkout browser-compat-data
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          repository: mdn/browser-compat-data
          path: bcd
          persist-credentials: false
      - name: Setup NodeJS
        uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          node-version-file: pr/.nvmrc
      - name: Install
        run: |
          set -eo pipefail
          cd bcd && npm ci | sed "s/^/[bcd] /" &
          cd base && npm ci | sed "s/^/[base] /" &
          cd pr && npm ci | sed "s/^/[pr] /" &
          wait
      - name: Build tests
        run: |
          set -eo pipefail
          cd base && npm run build:tests | sed "s/^/[base] /" &
          cd pr && npm run build:tests | sed "s/^/[pr] /" &
          wait
      - name: Feature coverage
        run: |
          set -eo pipefail
          cd base && npm run feature-coverage -- -l > ../base-features.txt | sed "s/^/[base] /" &
          cd pr && npm run feature-coverage -- -l > ../pr-features.txt | sed "s/^/[pr] /" &
          wait
        env:
          BCD_DIR: ../bcd
      - name: Diff
        run: git diff --color=always --no-index base-features.txt pr-features.txt || true

